---

global:

navigation:
    title: Bounded Infinity
    segment: /
    expanded: true
    children:
        -   title: Projects
            children:
                -   title: Blog
        -   title: Blog
            children:
                -   title: '2020'
                    children:
                        -   title: '09'
                            children:
                                -   title: '28'
                                    children:
                                        -   title: Place Holder
        -   title: About